SELECT 
    a.CAR_ID, 
    a.CAR_TYPE, 
    a.DAILY_FEE * 30 * (100 - b.DISCOUNT_RATE) / 100 AS "FEE"
FROM (
    SELECT *
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE (CAR_TYPE = '세단' OR CAR_TYPE = 'SUV') AND CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE START_DATE < DATE '2022-11-30' AND END_DATE > DATE '2022-11-01'
    )
) a
JOIN (
    SELECT CAR_TYPE, DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE (CAR_TYPE = '세단' OR CAR_TYPE = 'SUV') AND DURATION_TYPE = '30일 이상'
) b
ON a.CAR_TYPE = b.CAR_TYPE
WHERE a.DAILY_FEE * 30 * (100 - b.DISCOUNT_RATE) / 100 BETWEEN 500000 AND 2000000
ORDER BY "FEE" DESC, a.CAR_TYPE, a.CAR_ID;