SELECT 
    p.PRODUCT_ID,
    p.PRODUCT_NAME,
    SUM(p.PRICE * o.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT p
JOIN (
    SELECT * 
    FROM FOOD_ORDER
    WHERE TO_CHAR(PRODUCE_DATE, 'YYYY-MM') = '2022-05'
) o
ON o.PRODUCT_ID = p.PRODUCT_ID
GROUP BY p.PRODUCT_ID, p.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, p.PRODUCT_ID;
