SELECT FLAVOR
FROM (
    SELECT a.FLAVOR, SUM(a.TOTAL_ORDER) + SUM(b.TOTAL_ORDER) AS sum
    FROM FIRST_HALF a
    JOIN JULY b
    ON a.FLAVOR = b.FLAVOR
    GROUP BY a.FLAVOR
    ORDER BY sum DESC
)
OFFSET 0 ROWS FETCH NEXT 3 ROWS ONLY;