SELECT b.TITLE, b.BOARD_ID, r.REPLY_ID, r.WRITER_ID, r.CONTENTS, DATE_FORMAT(r.CREATED_DATE, '%Y-%m-%d')
FROM (SELECT * 
      FROM USED_GOODS_BOARD
      WHERE CREATED_DATE LIKE '2022-10-%') AS b
JOIN USED_GOODS_REPLY AS r
ON b.BOARD_ID = r.BOARD_ID
ORDER BY r.CREATED_DATE, b.TITLE